### ISSUE TITLE
Extra reference to TinyTris in main.py

### ISSUE THREAD

**Issue by a2** [TinyCircuits/tinycircuits.github.io#10]
The non-`/testing` main.py [still references](https://github.com/TinyCircuits/tinycircuits.github.io/blob/d3c8e07d628df50afbf49c4169f3acd7788fe8aa/ThumbyGames/main.py#L14) TinyTris before the rename to TinyBlocks.

**Comment by jmtinycircuits** [comment]
Thanks! Fixed in a0e97632b5fb8872470fe54a2fdaccca0e575cb2
