### ISSUE TITLE
Google Chrome 81.0.4044.92 + Linux not working

### ISSUE THREAD

**Issue by thor27** [TinyCircuits/tinycircuits.github.io#11]
Hello,
I'm trying to open https://tinycircuits.github.io/ on Google Chrome version 81.0.4044.92  on my Ubuntu machine but it's not working, I just get a gray screen. On the console is printed this error:
```
Uncaught SyntaxError: Unexpected reserved word
```

Screenshot
![image](https://user-images.githubusercontent.com/1656204/150610061-0cc7a6f8-08d6-45e2-9c0c-b275b4449a66.png)

Already tried to fully clean local storage, cache and cookies and no success

**Comment by jmtinycircuits** [comment]
Simple enough to fix. Will close on next merge.

**Comment by jmtinycircuits** [comment]
Fixed page is active, fetch it with ctrl+F5. Let me know

**Comment by thor27** [comment]
Hi,

Thanks for the quick reply and fix! Now I'm getting few other issues:

1. When I open I get:
```
Serial NOT supported in your browser! Use Microsoft Edge or Google Chrome
```

Even though I'm using an official google chrome build

2. Emulator has some visual issues:
![image](https://user-images.githubusercontent.com/1656204/150612455-6bb02aee-5582-403e-9bfa-548ebc0a3a4c.png)

3. Connect thumby does nothing

**Comment by thor27** [comment]
Hi, It seems the auto update of the browser was broken. I manually updated to the latest version and it's working now.

Thanks!
