### ISSUE TITLE
Microsoft Edge 99.0.1135.6 + Linux not accessing thumby file system

### ISSUE THREAD

**Issue by thor27** [TinyCircuits/tinycircuits.github.io#12]
Hi,

On MIcrosoft Edge version 99.0.1135.6 running on Ubuntu, I'm able to connect to thumby successfully but I can't see the filesystem or "upload as" the demo code:

![image](https://user-images.githubusercontent.com/1656204/150610378-d634b937-535e-48ae-9c59-e584571e0aab.png)

Emulator works fine.

**Comment by jmtinycircuits** [comment]
It looks like the Thumby is not connecting all the way. You should get a REPL that you can type commands into. Disconnect it, power cycle it, and reconnect.

Look at the shell in my image.
![image](https://user-images.githubusercontent.com/50587838/150611255-6d54e3ca-22e5-486e-a740-8aa11a8423c9.png)

Make sure you don't have any other IDE tabs open.

**Comment by thor27** [comment]
yes, it worked! strange that I tried exactly the same thing before and didn't worked that is why I posted the issue. But anyway, problem fixed :) thanks!
