### ISSUE TITLE
Inconsistencies regarding axis mirroring

### ISSUE THREAD

**Issue by Coolie2** [TinyCircuits/tinycircuits.github.io#6]
In trying to reduce the significant amount of space graphics take up in my game, I was testing the new axis mirroring feature, and realized that it seems that sprites mirrored downwards seem to always be off by a pixel or two. The documentation also mentions the first variable affecting x-axis mirroring and the second variable affecting y-axis mirroring, but this seems to reversed, as the second variable is what mirrors such sprites across the x axis.

**Comment by jmtinycircuits** [comment]
This should be fixed in the latest version of the Thumby API - take a look at https://github.com/TinyCircuits/tinycircuits.github.io/blob/master/testing/ThumbyAPI.md and test here https://tinycircuits.github.io/testing/
