### ISSUE TITLE
Typo or missing method implementation on /testing

### ISSUE THREAD

**Issue by a2** [TinyCircuits/tinycircuits.github.io#9]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/241156/147769693-890c57e2-15b0-4efa-a20e-8beb7b2add90.png">

`SSD1306` calls `write_window_cmd()` but I only see `write_window_cmd1()` and `write_window_cmd2()` implemented.

**Comment by jmtinycircuits** [comment]
This should be fixed by the latest commit 1055547db0f95a76187b4f97d3d9f1c813f5f029
